# Generated by Django 4.1.7 on 2023-03-21 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlesandcomments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_art', to='articlesandcomments.articles', verbose_name='Статья'),
        ),
    ]
