# Generated by Django 4.1.7 on 2023-03-22 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlesandcomments', '0003_remove_comment_art_alter_comment_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_auth', to='articlesandcomments.articles', verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_art', to='articlesandcomments.articles', verbose_name='Текст комментария'),
        ),
    ]
