# Generated by Django 4.1.7 on 2023-03-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articlesandcomments', '0004_alter_comment_name_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='art',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_art', to='articlesandcomments.articles', verbose_name='Исходная статья'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Автор комментария'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, verbose_name='Текст комментария'),
        ),
    ]
